runtime: nodejs20
service: fe-184  # Ganti nama service sesuai kebutuhan
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static  # Menyajikan file static seperti JS, CSS, dll.

  - url: /index.html
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*\.(js|css|html|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|otf))
    static_files: build/\1
    upload: build/(.*\.(js|css|html|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|otf))

  # Fallback handler untuk aplikasi single-page, mengarahkan semua rute ke index.html
  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html

default_expiration: "1d"  # Mengatur caching untuk file statis hingga 1 hari